images:
  cabri: tbeigbeder/cabri:v0.2.14-rc.1
  traefik: traefik:v2.11
  versions:
    app: "2.6.0"
    api: "2.6.0"
uid: 3002
fs_group: 2002
resources:
  app:
    requests:
      cpu: "0.25"
      memory: 256Mi
    limits:
      cpu: "0.5"
      memory: 512Mi
  api:
    requests:
      cpu: "0.25"
      memory: 256Mi
    limits:
      cpu: "0.5"
      memory: 512Mi
cabri_webapi:
  dss: "webapi+https://prca.otvl.org/prod-obs-otvl-web"
  user: "remote_cabri_login"
  password: "remote_cabri_password"
  config: "path/to/config"
  content: "path/to/content"
  assets: "path/to/assets"
env:
  AK: s3_access_key
  EP: s3_endpoint
  RG: s3_region
  SK: s3_secret_key
ingress:
  enabled: true
  # host: otvl-web-app.example.com, defaults to <release-name>.example.com
apr_credentials:
  - "weblogin:"
