apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: podinfo
          image: {{ .Values.image }}
          ports:
            - containerPort: 9898
          livenessProbe:
            periodSeconds: 60
            httpGet:
              path: /healthz
              port: 9898
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /readyz
              port: 9898
