---
# mockups/roles/kubebuilder/tasks/main.yml

- name: Install kubebuilder on the k3dev host
  include_role:
    name: commons
    tasks_from: install_from_url
  vars:
    url: "{{ values.kubebuilder.url }}"
    dload_name: "kubebuilder.1"
    sha: "{{ values.kubebuilder.sha }}"
    binary_name: "kubebuilder"
