---
# mockups/roles/k3all/configure_k3s/tasks/main.yml

- name: Create .kube directory
  file:
    dest: "/root/.kube"
    state: directory
    mode: "0700"

- name: Configure access to k3s api server
  ansible.builtin.copy:
    src: "{{ values.config_vars.local_devops_home }}/.k3s/{{ values.k3s.api_server_ansible_host }}/srv/data/otvl/k3s/k3s.yaml"
    dest: "/root/.kube/config"
    mode: "0600"
  become: true

###