apiVersion: v1
kind: Pod
metadata:
  name: ctr-reg
  labels:
    app.kubernetes.io/name: ctr-reg
spec:
  securityContext:
    runAsUser: 3002
    runAsGroup: 3002
    fsGroup: 3002
  containers:
    - name: ctr-reg
      image: registry:2.8
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: ctr-vol
          mountPath: /var/lib/registry
        - name: ctr-config-vol
          mountPath: /etc/docker/registry

  volumes:
    - name: ctr-vol
      persistentVolumeClaim:
        claimName: ctr-reg-pvc
    - name: ctr-config-vol
      configMap:
        name: ctr-reg-cmap

  restartPolicy: OnFailure
