apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  securityContext:
    runAsUser: {{ .Values.uid }}
    runAsGroup: {{ .Values.uid }}
    fsGroup: {{ .Values.uid }}
  containers:
    - name: ctr-reg
      image: {{ .Values.image }}
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: ctr-vol
          mountPath: /var/lib/registry
        - name: ctr-config-vol
          mountPath: /etc/docker/registry

  volumes:
    - name: ctr-vol
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-pvc
    - name: ctr-config-vol
      configMap:
        name: {{ .Release.Name }}-cmap

  restartPolicy: OnFailure
