apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-proxy
spec:
  securityContext:
    runAsUser: {{ .Values.uid }}
    runAsGroup: {{ .Values.uid }}
  containers:
    - name: ctr-proxy
      image: {{ .Values.images.traefik }}
      command: ["/usr/local/bin/traefik"]
      args: ["--configFile=/traefik/static-config.yml"]
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: ctr-config-vol
          mountPath: /traefik
  volumes:
    - name: ctr-config-vol
      configMap:
        name: {{ .Release.Name }}-proxy-cmap
  restartPolicy: OnFailure
