{% if 'build_group' in vars.group_names or 'k3dev_group' in vars.group_names %}
address        = "/run/containerd/containerd.sock"
{% else %}
address        = "/run/k3s/containerd/containerd.sock"
namespace      = "k8s.io"
{% endif %}