---
# mockups/roles/operator_framework/tasks/main.yml

- name: Install operator framework on the k3dev host
  include_role:
    name: commons
    tasks_from: install_from_url
  vars:
    url: "{{ values.operator_sdk.url }}"
    dload_name: "operator_sdk.1"
    sha: "{{ values.operator_sdk.sha }}"
    binary_name: "operator-sdk"
