mirrors:
  "{{ otvl.ctr.ingress_host }}":
    endpoint:
      - "https://{{ otvl.ctr.ingress_host }}"
configs:
  "{{ otvl.ctr.ingress_host }}":
    auth:
      username: "{{ otvl.ctr.login }}"
      password: "{{ otvl.ctr.password }}"
    tls:
      insecure_skip_verify: {{ otvl.ctr.skip_verify | default(false) }}
