apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: "tcp-port"
      port: 2000
      protocol: TCP
      nodePort: 32000
