replicaCount: 2
images:
  nginx: nginxinc/nginx-unprivileged:1.25.3
  git: bitnami/git:2.43.1
  busybox: busybox:1.36.1
git_repo:
  url: https://github.com/t-beigbeder/otvl_blog
  branch: master
resources:
  requests:
    cpu: "0.25"
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi
ingress:
  enabled: true
  # host: test-nginx.example.com, defaults to <release-name>.example.com
