apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-api
  serviceName: {{ .Release.Name }}-api
  template:
    metadata:
      name: {{ .Release.Name }}-api
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-api
    spec:
      securityContext:
        runAsUser: {{ .Values.uid }}
        runAsGroup: {{ .Values.uid }}
        fsGroup: {{ .Values.fs_group }}
      containers:
        - name: api
          image: {{ .Values.images.cabri }}
          env:
            {{- include "podenv-from-env" . | trim | nindent 12 }}
          command:
            - sh
            - /api-cmap/run-cabri-webapi.sh
            {{- include "dsss-args-from-dsss" . | trim | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 3000
          livenessProbe:
            periodSeconds: 60
            httpGet:
              path: /{{ .Values.check_url }}/check
              port: 3000
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /{{ .Values.check_url }}/check
              port: 3000
          volumeMounts:
            - name: dss-vol
              mountPath: /data
            - name: api-cmap-vol
              mountPath: /api-cmap
      initContainers:
        - name: init
          image: {{ .Values.images.cabri }}
          env:
            {{- include "podenv-from-env" . | trim | nindent 12 }}
          command:
            - sh
            - /api-cmap/init-cabri-webapi.sh
            {{- include "dsss-args-from-dsss" . | trim | nindent 12 }}
          volumeMounts:
            - name: dss-vol
              mountPath: /data
            - name: api-cmap-vol
              mountPath: /api-cmap

      volumes:
        - name: dss-vol
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        - name: api-cmap-vol
          configMap:
            name: {{ .Release.Name }}-api-cmap
