apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  securityContext:
    runAsUser: {{ .Values.uid }}
    runAsGroup: {{ .Values.uid }}
    fsGroup: {{ .Values.fs_group }}
  containers:
    - name: api
      image: {{ .Values.images.cabri }}
      env:
        {{- include "podenv-from-var" . | trim | nindent 8 }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      ports:
        - containerPort: 3000
      livenessProbe:
        periodSeconds: 60
        httpGet:
          path: /{{ first .Values.urls }}/check
          port: 3000
      readinessProbe:
        periodSeconds: 60
        httpGet:
          path: /{{ first .Values.urls }}/check
          port: 3000
      volumeMounts:
        - name: dss-vol
          mountPath: /data
  initContainers:
    - name: init
      image: {{ .Values.images.cabri }}
      env:
        {{- include "podenv-from-var" . | trim | nindent 8 }}
      command: ["sh", "/api-cmap/init-cabri-webapi.sh", "arg"]
      volumeMounts:
        - name: dss-vol
          mountPath: /data
        - name: api-cmap-vol
          mountPath: /api-cmap

  volumes:
    - name: dss-vol
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-pvc
    - name: api-cmap-vol
      configMap:
        name: {{ .Release.Name }}-api-cmap

  restartPolicy: OnFailure
