apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  securityContext:
    runAsUser: {{ .Values.uid }}
    runAsGroup: {{ .Values.uid }}
    fsGroup: {{ .Values.fs_group }}
  containers:
    - name: api
      image: {{ .Values.images.cabri }}
      resources:
          {{- toYaml .Values.resources | nindent 10 }}
      ports:
        - containerPort: 3000
      livenessProbe:
        periodSeconds: 60
        httpGet:
          path: /{{ first .Values.urls }}/check
          port: 3000
      readinessProbe:
        periodSeconds: 60
        httpGet:
          path: /{{ first .Values.urls }}/check
          port: 3000
      volumeMounts:
        - name: dss-vol
          mountPath: /data
        - name: api-config-vol
          mountPath: /init-scripts
  initContainers:
    - name: init
      image: {{ .Values.images.cabri }}
      command: ["sh", "/init-scripts/init-cabri-webapi.sh", "arg"]
      volumeMounts:
        - name: workdir
          mountPath: /workdir
        - name: api-config-vol
          mountPath: /init-scripts

  volumes:
    - name: dss-vol
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-pvc
    - name: workdir
      emptyDir: {}
    - name: api-config-vol
      configMap:
        name: {{ .Release.Name }}-api-cmap

  restartPolicy: OnFailure
