apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-cmap
data:
  "init-cabri-webapi.sh": |
    copt="--pfile /etc/cabri-pfile --cdir /data/cdir"
    ccmd="/usr/local/bin/cabri $copt"
    mkdir -p /data/cdir /data/backups/cdir && \
      $ccmd cli config --get
    for dss in $* ; do
      sh /api-cmap/init-dss.sh $dss
    done
    ts=`date +%Y%m%d-%H:%M:%S`
    tar czf /data/backups/cdir/cdir.$ts.tgz data/cdir
  "init-dss.sh": |
    dt=`echo $1 | cut -d':' -f1`
    dn=`echo $1 | cut -d':' -f2`
    echo >&2 "Initializing DSS $dt:/data/dss/$dn"
    copt="--pfile /etc/cabri-pfile --cdir /data/cdir"
    ccmd="/usr/local/bin/cabri $copt"
    if [ ${dt} = "obs" -o ${dt} = "xobs" ] ; then
      OBS_ENV="--obsrg ${RG} --obsep ${EP} --obsct $dn --obsak ${AK} --obssk ${SK}"
      LOG_OBS_ENV="--obsrg ${RG} --obsep ${EP} --obsct $dn --obsak ${AK} --obssk <secret>"
      $ccmd cli s3tools $OBS_ENV --cnx
      if [ $? -ne 0 ] ; then echo >&2 "${LOG_OBS_ENV} has connexion issues" ; fi
    fi
    ts=`date +%Y%m%d-%H:%M:%S`
    if [ ! -d /data/dss/$dn ] ; then
      mkdir -p /data/dss/$dn /data/backups/$dn && \
      echo >&2 $ccmd cli dss make $OBS_ENV -s m --ximpl bdb $dt:/data/dss/$dn && \
      $ccmd cli dss make $OBS_ENV -s m --ximpl bdb $dt:/data/dss/$dn && \
      echo >&2 $ccmd cli dss reindex $dt:/data/dss/$dn && \
      $ccmd cli dss reindex $dt:/data/dss/$dn && \
      tar czf /data/backups/$dn/$dn.$ts.tgz data/dss/$dn
    else
      echo >&2 $ccmd cli dss unlock $dt:/data/dss/$dn && \
      $ccmd cli dss unlock $dt:/data/dss/$dn && \
      tar czf /data/backups/$dn/$dn.$ts.tgz data/dss/$dn
    fi
  "run-cabri-webapi.sh": |
    copt="--pfile /etc/cabri-pfile --cdir /data/cdir"
    ccmd="/usr/local/bin/cabri $copt"
    $ccmd cli config --get
    urls=
    for dss in $* ; do
      urls="$urls `sh /api-cmap/get-dss.sh $dss`"
    done
    cmd="$ccmd webapi $urls --haslog"
    echo $cmd
    ${cmd}
  "get-dss.sh": |
    dt=`echo $1 | cut -d':' -f1`
    dn=`echo $1 | cut -d':' -f2`
    echo "${dt}+http://0.0.0.0:3000/data/dss/${dn}@${dn}"
