apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy-cmap
data:
  "static-config.yml": |
    global:
      sendAnonymousUsage: true
    log:
      level: INFO
    accessLog: {}
    providers:
      file:
        filename: /traefik/dynamic-conf.yml
        watch: true
    entryPoints:
      web:
        address: ':3000'

  "dynamic-conf.yml": |
    http:
      routers:
        to-api:
          rule: "PathPrefix(`/`)"
          middlewares:
            - basic-auth
          service: api
      middlewares:
        basic-auth:
          basicAuth:
            users:
              {{- include "auth-users-from-credentials" . | trim | nindent 14 }}
      services:
        "api":
          loadBalancer:
            servers:
              - url: "http://{{ .Release.Name }}-api:3000"
