---
# otvl/roles/k8s_client/configure_k3s/tasks/main.yml

- name: Configure access to k3s api server
  ansible.builtin.copy:
    src: "{{ otvl.config_vars.devops_home }}/.k3s/{{ otvl.k3s.api_server_ansible_host }}/srv/data/otvl/k3s/k3s.yaml"
    remote_src: true
    dest: "{{ otvl.config_vars.devops_home }}/.kube/config"
    mode: "0600"
    owner: "{{ otvl.config_vars.devops_user }}"
    group: "{{ otvl.config_vars.devops_user }}"
  become: true

###