---
# default otvl variable for otvl_devops_tools playbooks and roles

default_otvl:
  debug: false
  config_paths:
    delivery: /otvl/delivery
    data: /otvl/data
  config_vars:
    admin_user: otvl_admin_user
    admin_key: otvl_admin_key
    devops_user: devops
    devops_key: id_rsa_devops
    otvl_devops_tools_repo: "https://github.com/t-beigbeder/otvl_devops_tools"
    otvl_devops_tools_version: "main"
    otvl_ans_inv_local_git_repo_tgz: /path/to/gitbare/otvl_anprin.git.tar.gz
  cabri:
    release: "v0.2.13"
    sha: "29f47154e88f75e82eda224bfa9b3a782196bfc08e53fb5bffa833f355c073d3"
  kubectl:
    url: "https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl"
    sha: "7816d067740f47f949be826ac76943167b7b3a38c4f0c18b902fffa8779a5afa"
  cmctl:
    release_url: "https://github.com/cert-manager/cert-manager/releases/download/v1.12.7/cmctl-linux-amd64.tar.gz"
    sha: "bf47f11c8fc637ea18da84e36ab7c9ad5e40449fd04afcbbc25ce5ae3f22d038"
  helm:
    release_url: "https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz"
    sha: "f43e1c3387de24547506ab05d24e5309c0ce0b228c23bd8aa64e9ec4b8206651"
  opentofu:
    release_url: "https://github.com/opentofu/opentofu/releases/download/v1.6.2/tofu_1.6.2_linux_amd64.zip"
    sha: "18277462e0ded513e47fb3e041911dfd14f4ad3721d53ee2f0c709fa810b8cf0"
  k3s:
    traefik:
      customize: true
#    api_server: ovhk6-loc
#    api_server_ansible_host: ovhk6
    default_namespace: "default"
  cert_manager:
    release_url: "https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.yaml"
    sha: "af39d0d73641327d921647cf6add447f3dfdc0c431e43820b227ab249e3728d9"
    le_url: "https://acme-v02.api.letsencrypt.org/directory"
    le_email: "acme@example.com"
  ctr:
    release: otvl-ctr
    image: "registry:2.8"
    uid: 3002
    fs_group: 2002
    ingress_host: ctr.example.com
    login: ctrlogin
    password: ""
    apr_credentials: "ctr:"
