#cloud-config
write_files:
  - content: |
      #!/bin/sh
      ec2_git_repo="https://github.com/t-beigbeder/otvl_devops_tools"
      ec2_git_branch="bdev2"
      git_local="/root/clinit/otvl_devops_tools"
      echo `date`: command $0 is starting with profile ${ec2_profile}
      apt-get update && \
        apt-get install -y --no-install-recommends git jq curl python3-systemd fail2ban && \
        mkdir -p /root/clinit && \
        cd /root/clinit && \
        rm -rf $git_local && \
        git clone ${ec2_git_repo} -b ${ec2_git_branch} && \
        cd $git_local && \
        chmod 700 src/shell/mockups/k3s_ha_aws/mockup_k3s_ha_aws_cloud_init_from_git.sh && \
        src/shell/mockups/k3s_ha_aws/mockup_k3s_ha_aws_cloud_init_from_git.sh && \
        echo `date`: command $0 is exiting || exit 1
      exit 0
    path: /root/bin/otvl_cloud_init.sh
    owner: root:root
    permissions: '0750'

runcmd:
  - [ /root/bin/otvl_cloud_init.sh ]
