#cloud-config
write_files:
  - content: |
        #!/bin/sh
        export CI_LHN=${tf_loc_hostname}
        export CI_LIP4=${tf_loc_ipv4}
        export CI_DOT_REPO=${tf_dot_repo}
        export CI_DOT_BRANCH=${tf_dot_branch}
        export CI_ROPS_REPO=${tf_rops_repo}
        export CI_INSTALL_ENV=${tf_install_env}
        export HOME=/root
        echo `date`: command $0 is starting
        apt-get update && \
        apt-get install -y --no-install-recommends git jq yq curl && \
        mkdir -p /root/clinit /root/locgit && cd /root/locgit && \
        git clone --single-branch --branch $CI_DOT_BRANCH $CI_DOT_REPO && \
        cd `basename $CI_DOT_REPO`/src/shell/init_vm && \
        ./cloud_init_install.sh && \
        true || exit 1
        echo `date`: command $0 is exiting
        exit 0

    path: /root/bin/otvl_cloud_init.sh
    owner: root:root
    permissions: '0750'
runcmd:
  - [ /root/bin/otvl_cloud_init.sh ]
