#cloud-config
write_files:
  - content: |
        #!/bin/sh
        export CI_LHN=${tf_loc_hostname}
        export CI_LIP4=${tf_loc_ip_v4}
        export CI_DOT_REPO=${tf_dot_repo}
        export CI_DOT_BRANCH=${tf_dot_branch}
        export CI_ROPS_REPO=${tf_rops_repo}
        export CI_INSTALL_ENV=${tf_install_env}
        export CI_PRIK=${tf_prik}
        export CI_GOV=${tf_go_version}
        export CI_PXHN=${tf_bssms_proxy_hostname}
        export CI_PXPT=${tf_bssms_proxy_port}
        export HOME=/root
        echo `date`: command $0 is starting
        apt-get update && \
        apt-get install -y --no-install-recommends git jq yq curl && \
        mkdir -p /root/clinit /root/locgit && cd /root/locgit && \
        curl -L https://go.dev/dl/go$CI_GOV.linux-amd64.tar.gz -o go.tgz && \
        rm -rf /usr/local/go && tar -C /usr/local -xzf go.tgz && rm go.tgz && \
        git clone --single-branch --branch $CI_DOT_BRANCH $CI_DOT_REPO && \
        cd otvl_devops_tools/src/go/bssms/ && /usr/local/go/bin/go build -o /usr/local/bin ./... && \
        cd  /root/clinit && rm -rf otvl_devops_tools && rm -rf /usr/local/go && \
        true || exit 1
        if [ "CI_PRIK" ] ; then
            export CI_UUID=`curl http://169.254.169.254/openstack/latest/meta_data.json | jq -r .uuid`
            export CI_MAC=`ip -j ad | jq -r .[1].address`
            export CI_ADDR=`ip -4 -j ad | jq -r .[1].addr_info[0].local`
            cmd="/usr/local/bin/bssms in -pxa $CI_PXHN:$CI_PXPT -uuid $CI_UUID -mac $CI_MAC -ip $CI_ADDR -prik $CI_PRIK --js bssms.json"
            echo Running $cmd
            $cmd
        else
            echo "no secrets, not running bssms installer"
        fi
        cd /root/locgit/`basename $CI_DOT_REPO`/src/shell/init_vm && \
        ./cloud_init_install.sh && \
        true || exit 1
        echo `date`: command $0 is exiting
        exit 0

    path: /root/bin/otvl_cloud_init.sh
    owner: root:root
    permissions: '0750'

  - encoding: b64
    content: ${tf_b64_id_rsa_rops}
    path: /root/.ssh/id_rsa_rops
    permissions: '0400'
runcmd:
  - [ /root/bin/otvl_cloud_init.sh ]
