apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-app
  ports:
    - name: "app-port"
      port: 80
      protocol: TCP
