images:
  cabri: tbeigbeder/cabri:v0.2.14-rc.1
  traefik: traefik:v2.11
uid: 3002
fs_group: 2002
resources:
  requests:
    cpu: "0.25"
    memory: 1Gi
  limits:
    cpu: "1"
    memory: 2Gi
ingress:
  enabled: true
  # host: otvl-cabri.example.com, defaults to <release-name>.example.com
urls:
  - data
env:
  AK: s3_access_key
  EP: s3_endpoint
  RG: s3_region
  SK: s3_secret_key
