apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: server
          image: {{ .Values.images.ht3mock }}
          ports:
            - containerPort: 9443
          livenessProbe:
            periodSeconds: 60
            tcpSocket:
              port: 9443
          readinessProbe:
            periodSeconds: 60
            tcpSocket:
              port: 9443
