apiVersion: v1
kind: Service
metadata:
  name: h2-{{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: h2-{{ .Release.Name }}
  type: LoadBalancer
  ports:
    - name: "tcp-port"
      port: 9443
      protocol: TCP
