apiVersion: v1
kind: Service
metadata:
  name: h2-{{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: h2-{{ .Release.Name }}
{{- if .Values.service.nodePort.enabled }}
  type: NodePort
  ports:
    - name: "tcp-port"
      nodePort: {{ .Values.service.port2 }}
      protocol: TCP
      port: 9443
{{- else }}
  type: LoadBalancer
  ports:
    - name: "tcp-port"
      port: {{ .Values.service.port2 }}
      targetPort: 9443
      protocol: TCP
{{- end }}
