apiVersion: v1
kind: Service
metadata:
  name: h3-{{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: h3-{{ .Release.Name }}
  type: LoadBalancer
  ports:
    - name: "udp-port"
      port: 9443
      protocol: UDP
