apiVersion: v1
kind: Service
metadata:
  name: ht3-{{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: ht3-{{ .Release.Name }}
  ports:
    - name: "udp-port"
      port: 9443
      protocol: UDP
