apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: "tcp-port"
      port: 9443
      protocol: UDP
      nodePort: 30443
