- hosts: "*"
  gather_facts: False
  tasks:
    - name: Load default variables
      include_vars:
        dir: vars/defaults
    - name: Combine default with actual values config data
      set_fact:
        cbd_values: "{{ default_values | combine(values, recursive=True) }}"
  tags: always

- hosts: bastion_group
  gather_facts: False
  become: yes
  roles:
    - devops_tools
    - k8s_client
  vars:
    values: "{{ cbd_values }}"
  tags:
    - bastion

- hosts: bastion_controlled_group
  gather_facts: False
  become: yes
  roles:
    - bastion_controlled
  vars:
    values: "{{ cbd_values }}"
  tags:
    - bastion

- hosts: k3dev_group
  gather_facts: False
  become: yes
  roles:
    - k3dev
    - golang
    - kubebuilder
    - containerd
    - nerdctl
    - buildkit
  vars:
    values: "{{ cbd_values }}"
  tags:
    - k3dev

- hosts: k3s_simple_group
  gather_facts: False
  become: yes
  roles:
    - k3s_simple
    - nerdctl
  vars:
    values: "{{ cbd_values }}"
  tags:
    - k3s_simple

- hosts: bastion_group
  gather_facts: False
  become: yes
  roles:
    - k8s_client/configure_k3s
    - cert_manager
  vars:
    values: "{{ cbd_values }}"
  tags:
    - k3s_simple

- hosts: k3dev_group
  gather_facts: False
  become: yes
  roles:
    - k3dev/configure_k3s
  vars:
    values: "{{ cbd_values }}"
  tags:
    - k3s_simple
