---
# mockups/roles/cilium/tasks/main.yml

- name: Install cilium
  block:
    - debug: var=kapp_message
    - command:
        cmd: "cilium install --version {{ values.cilium.version }}"
      register: cilium
    - debug: var=cilium.cmd
    - debug: var=cilium.stderr_lines
    - debug: var=cilium.stdout_lines
  when: values.k3s.cilium

- name: pause to check k3s
  pause:

###