---
# mockups/roles/k3all/tasks/main.yml

- name: Install debian dev packages on the k3dev host
  ansible.builtin.apt:
    pkg:
      - make
      - git
    update_cache: "{{ values.prod }}"
    install_recommends: no
    state: present

- name: Checkout git otvl_devops_tools on k3dev once
  git:
    repo: "{{ values.config_vars.otvl_devops_tools_repo }}"
    version: "{{ values.config_vars.otvl_devops_tools_version }}"
    dest: "/root/locgit/otvl/otvl_devops_tools"
    depth: 1
    update: false
    recursive: no
    force: no
