# mockups/roles/flux/cluster/tasks/main.yml

- name: Install the fluxcd in the cluster
  shell: "flux bootstrap github --owner={{ values.github.user }} --token={{ values.github.token }} --repository=otvl_flux --branch=main --path=./clusters/{{ values.k3s.api_server_ansible_host }} --personal"