{% if 'k3s_simple_group' in vars.group_names %}
address        = "/run/k3s/containerd/containerd.sock"
namespace      = "k8s.io"
{% else %}
address        = "/run/containerd/containerd.sock"
{% endif %}