# mockups/roles/commons/tasks/kapply_from_template.yml
# kubectl apply manifest downloaded from url
# vars:
#   template: template
#   kapp_message: message to be displayed during kubectl apply

- name: "{{ kapp_message }}"
  block:
    - command:
        cmd: "kubectl apply -f -"
        stdin: "{{ lookup('template', template) }}"
      become_user: "{{ values.config_vars.devops_user }}"
      register: kapply
    - debug: var=kapply.cmd
    - debug: var=kapply.stderr_lines
    - debug: var=kapply.stdout_lines
