---
# mockups/roles/commons/tasks/srv_dirs.yml

- name: Create server root directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ values.config_paths.data }}"
    - "{{ values.config_paths.delivery }}"

###