---
# otvl/roles/services/otvl_web/tasks/main.yml

- name: Loop over otvl_web site entries for deploying pods
  include_tasks: deploy_site.yml
  loop: "{{ otvl.otvl_web_services }}"
  loop_control:
    loop_var: current_item
  when: not (current_item.skip_hdeploy | default(false))

###