---
# otvl/roles/local_path_provisioner/tasks/main.yml

- name: Here otvl/roles/local_path_provisioner/tasks/main.yml
  include_role:
    name: commons
    tasks_from: kapply_from_url
  vars:
    url: "{{ otvl.local_path_provisioner.release_url }}"
    sha: "{{ otvl.local_path_provisioner.sha }}"
    dload_name: "local-path-storage.yaml"
    kapp_message: "Install local-path-provisioner on the k3s cluster"

###