apiVersion: otvl.otvl.org/v1beta1
kind: Bar
metadata:
  labels:
    app.kubernetes.io/name: otvl-bar
    app.kubernetes.io/managed-by: kustomize
  name: bar-sample
spec:
  # TODO(user): Add fields here
