[worker.oci]
  enabled = false

{% if 'k3s_simple_group' in vars.group_names %}
[worker.containerd]
  enabled = true
  address = "/run/k3s/containerd/containerd.sock"
  namespace = "k8s.io"
{% else %}
[worker.containerd]
  enabled = true
  address = "/run/containerd/containerd.sock"
{% endif %}
