# permissions for end users to view bars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: otvl-bar
    app.kubernetes.io/managed-by: kustomize
  name: bar-viewer-role
rules:
- apiGroups:
  - otvl.otvl.org
  resources:
  - bars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - otvl.otvl.org
  resources:
  - bars/status
  verbs:
  - get
