# permissions for end users to view bars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: barsvc-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: otvl-barsvc
    app.kubernetes.io/part-of: otvl-barsvc
    app.kubernetes.io/managed-by: kustomize
  name: barsvc-viewer-role
rules:
- apiGroups:
  - otvl.otvl.org
  resources:
  - bars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - otvl.otvl.org
  resources:
  - bars/status
  verbs:
  - get
