- hosts: "*"
  gather_facts: False
  tasks:
    - name: Load default variables
      include_vars:
        dir: vars/defaults
    - name: Combine default with actual otvl config data
      set_fact:
        cbd_otvl: "{{ default_otvl | combine(otvl, recursive=True) }}"
  tags: always

- hosts: bastion_group
  gather_facts: False
  become: yes
  roles:
    - devops_tools
  vars:
    otvl: "{{ cbd_otvl }}"
  tags:
    - bastion
